### PR TITLE
Adding CPOOL assets to Trust Wallet

### PR DESCRIPTION
**Pull request by korzhanov**
https://github.com/clearpool-finance/website/issues/603

### CODE REVIEW

**Review by zolotokrylin — CHANGES_REQUESTED** [review]
What about CPOOL on Polygon?

**Comment by zolotokrylin** [comment]
@drugz what are you busy with now?

**Comment by korzhanov** [comment]
> What about CPOOL on Polygon?

@zolotokrylin  I finally figured it out. Done. Please check

**Comment by zolotokrylin** [comment]
@drugz thanks.

**Pull request merged**
